on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: ["Inventories", "Orchestrators", "Orders", "Payments", "Stocks"]

    steps:
      - name: List folder structure for each service
        run: |
          echo "Listing the folder structure"
          ls -R
          
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Service Lowercase
        id: set_service_lowercase
        run: |
          echo "service_lowercase=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.service }}/${{ matrix.service }}.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}-api:latest
