on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: ["Inventories", "Orchestrators", "Orders", "Payments", "Stocks"]
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Service Lowercase
        id: set_service_lowercase
        run: |
          echo "service_lowercase=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set Cache Image for Docker Layer Caching
        id: docker-cache
        run: |
          echo "::set-output name=cache-image::ghcr.io/${{ github.actor }}/cache-${{ steps.set_service_lowercase.outputs.service_lowercase }}:build"
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.service }}/${{ matrix.service }}.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}-api:latest
            ghcr.io/${{ github.actor }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}-api:${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.docker-cache.outputs.cache-image }}
          cache-to: type=registry,ref=${{ steps.docker-cache.outputs.cache-image }},mode=push
