on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: []  # We'll populate this dynamically

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: List folder structure
        run: |
          echo "Listing the folder structure"
          # List all directories that match the service pattern (e.g., service folders in your repo)
          directories=$(find . -maxdepth 2 -type d -name "*.API" | sed 's|^\./||')
          echo "Directories found: $directories"
          # Format the directories into a space-separated list
          echo "service_list=$directories" >> $GITHUB_ENV

      - name: Set matrix for services
        run: |
          echo "Setting matrix for services from folder structure"
          # Convert the list of directories into a space-separated matrix
          echo "::set-output name=service_list::$(echo $service_list | tr ' ' '\n')"
      
      - name: Set Service Lowercase
        id: set_service_lowercase
        run: |
          service_lowercase=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')
          echo "service_lowercase=$service_lowercase" >> $GITHUB_ENV
          echo "::set-output name=service_lowercase::$service_lowercase"

      - name: Log in to GitHub Container
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service }}/${{ matrix.service }}.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}-api:latest
