on:
  pull_request:

jobs:
  dependency:

    steps:
        uses: actions/checkout@v4

        uses: actions/setup-dotnet@v4

        run: dotnet restore

        uses: actions/dependency-review-action@v4
