on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  actions: read
  contents: read
  security-events: write read

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']
        dotnet-version: ['9.0.x'] # Use .NET 9

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3 # Pin to specific version for stability

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3 # Pin to a specific version

    # Cache .NET dependencies
    - name: Cache .NET dependencies
      uses: actions/cache@v3 # Pin to a specific version
      with:
        path: '**/obj/project.assets.json'
        key: dotnet-dependencies-${{ matrix.dotnet-version }}-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/Directory.Build.props') }} # Use project files for more deterministic cache key
        restore-keys: |
          dotnet-dependencies-${{ matrix.dotnet-version }}-

    # Restore NuGet dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Run tests (if applicable)
    - name: Run tests
      run: dotnet test --configuration Release --no-build
